In [2]:
import pandas as pd
import numpy as np 

In [3]:
data=pd.read_csv("Filtered.csv")
data.head()

StepNumber  BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  \
0           0           0.0            0.0           0.0      -126.0   
1           1           0.0            5.0           0.0      -126.0   
2           2           0.0           10.0           0.0      -126.0   
3           0           0.0            0.0           0.0      -126.0   
4           1           0.0            0.0           0.0      -126.0   

   ElbowRoll  HandPitch  GripperRotation  EndEffectorX  EndEffectorY  ...  \
0        0.0      126.0             48.0      0.000000      0.000000  ...   
1        0.0      126.0             48.0     -0.000136      0.515677  ...   
2        0.0      126.0             48.0     -0.000085      0.504809  ...   
3        0.0      126.0             48.0      0.000000      0.000000  ...   
4        0.0      121.0             48.0     -0.000163      0.504255  ...   

   Gripped  IsGood  BaseRight  BaseLeft  ShoulderDown  ShoulderUp  ElbowDown  \
0    False    True          0         0             0           0          0   
1    False    True          0         0             1           0          0   
2    False    True          0         0             1           0          0   
3    False    True          0         0             0           0          0   
4    False    True          0         0             0           0          0   

   ElbowUp  HandDown  HandUp  
0        0         0       0  
1        0         0       0  
2        0         0       0  
3        0         0       0  
4        0         0       1  

[5 rows x 35 columns]

In [4]:
data["Target"]=data["BaseRight"]
data.head()

StepNumber  BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  \
0           0           0.0            0.0           0.0      -126.0   
1           1           0.0            5.0           0.0      -126.0   
2           2           0.0           10.0           0.0      -126.0   
3           0           0.0            0.0           0.0      -126.0   
4           1           0.0            0.0           0.0      -126.0   

   ElbowRoll  HandPitch  GripperRotation  EndEffectorX  EndEffectorY  ...  \
0        0.0      126.0             48.0      0.000000      0.000000  ...   
1        0.0      126.0             48.0     -0.000136      0.515677  ...   
2        0.0      126.0             48.0     -0.000085      0.504809  ...   
3        0.0      126.0             48.0      0.000000      0.000000  ...   
4        0.0      121.0             48.0     -0.000163      0.504255  ...   

   IsGood  BaseRight  BaseLeft  ShoulderDown  ShoulderUp  ElbowDown  ElbowUp  \
0    True          0         0             0           0          0        0   
1    True          0         0             1           0          0        0   
2    True          0         0             1           0          0        0   
3    True          0         0             0           0          0        0   
4    True          0         0             0           0          0        0   

   HandDown  HandUp  Target  
0         0       0       0  
1         0       0       0  
2         0       0       0  
3         0       0       0  
4         0       1       0  

[5 rows x 36 columns]

In [5]:
for i in range(len(data["Target"])):
    if data["BaseRight"][i]==1:
        data["Target"][i]=1
    elif data["BaseLeft"][i]==1:
        data["Target"][i]=2
    elif data["ShoulderDown"][i]==1:
        data["Target"][i]=3
    elif data["ShoulderUp"][i]==1:
        data["Target"][i]=4
    elif data["ElbowDown"][i]==1:
        data["Target"][i]=5
    elif data["ElbowUp"][i]==1:
        data["Target"][i]=6
    elif data["HandDown"][i]==1:
        data["Target"][i]=7
    elif data["HandUp"][i]==1:
        data["Target"][i]=8  # hand down
    else:
        data["Target"][i]=0
data.head()

<ipython-input-5-83ea36357936>:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Target"][i]=0
<ipython-input-5-83ea36357936>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Target"][i]=3
<ipython-input-5-83ea36357936>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Target"][i]=8  # hand down
<ipython-input-5-83ea36357936>:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFram

StepNumber  BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  \
0           0           0.0            0.0           0.0      -126.0   
1           1           0.0            5.0           0.0      -126.0   
2           2           0.0           10.0           0.0      -126.0   
3           0           0.0            0.0           0.0      -126.0   
4           1           0.0            0.0           0.0      -126.0   

   ElbowRoll  HandPitch  GripperRotation  EndEffectorX  EndEffectorY  ...  \
0        0.0      126.0             48.0      0.000000      0.000000  ...   
1        0.0      126.0             48.0     -0.000136      0.515677  ...   
2        0.0      126.0             48.0     -0.000085      0.504809  ...   
3        0.0      126.0             48.0      0.000000      0.000000  ...   
4        0.0      121.0             48.0     -0.000163      0.504255  ...   

   IsGood  BaseRight  BaseLeft  ShoulderDown  ShoulderUp  ElbowDown  ElbowUp  \
0    True          0         0             0           0          0        0   
1    True          0         0             1           0          0        0   
2    True          0         0             1           0          0        0   
3    True          0         0             0           0          0        0   
4    True          0         0             0           0          0        0   

   HandDown  HandUp  Target  
0         0       0       0  
1         0       0       3  
2         0       0       3  
3         0       0       0  
4         0       1       8  

[5 rows x 36 columns]

In [6]:
data.columns

Index(['StepNumber', 'BaseRotation', 'ShoulderPitch', 'ShoulderRoll',
       'ElbowPitch', 'ElbowRoll', 'HandPitch', 'GripperRotation',
       'EndEffectorX', 'EndEffectorY', 'EndEffectorZ', 'TargetX', 'TargetY',
       'TargetZ', 'DistanceToTarget', 'DeltaBaseRotation',
       'DeltaShoulderPitch', 'DeltaShoulderRoll', 'DeltaElbowPitch',
       'DeltaElbowRoll', 'DeltaHandPitch', 'DeltaGripperRotation', 'DeltaX',
       'DeltaY', 'DeltaY.1', 'Gripped', 'IsGood', 'BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp', 'Target'],
      dtype='object')

In [7]:
data.rename(columns={'DeltaY.1':'DeltaZ'}, inplace=True)

In [8]:
data.columns

Index(['StepNumber', 'BaseRotation', 'ShoulderPitch', 'ShoulderRoll',
       'ElbowPitch', 'ElbowRoll', 'HandPitch', 'GripperRotation',
       'EndEffectorX', 'EndEffectorY', 'EndEffectorZ', 'TargetX', 'TargetY',
       'TargetZ', 'DistanceToTarget', 'DeltaBaseRotation',
       'DeltaShoulderPitch', 'DeltaShoulderRoll', 'DeltaElbowPitch',
       'DeltaElbowRoll', 'DeltaHandPitch', 'DeltaGripperRotation', 'DeltaX',
       'DeltaY', 'DeltaZ', 'Gripped', 'IsGood', 'BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp', 'Target'],
      dtype='object')

In [9]:
data.drop(['StepNumber', 'DistanceToTarget', 'DeltaBaseRotation',
       'DeltaShoulderPitch', 'DeltaShoulderRoll', 'DeltaElbowPitch',
       'DeltaElbowRoll', 'DeltaHandPitch', 'DeltaGripperRotation', 'DeltaX',
       'DeltaY', 'DeltaZ', 'Gripped', 'IsGood', 'BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp'], axis = 1, inplace = True)
data.head()

BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  ElbowRoll  \
0           0.0            0.0           0.0      -126.0        0.0   
1           0.0            5.0           0.0      -126.0        0.0   
2           0.0           10.0           0.0      -126.0        0.0   
3           0.0            0.0           0.0      -126.0        0.0   
4           0.0            0.0           0.0      -126.0        0.0   

   HandPitch  GripperRotation  EndEffectorX  EndEffectorY  EndEffectorZ  \
0      126.0             48.0      0.000000      0.000000      0.000000   
1      126.0             48.0     -0.000136      0.515677      0.036158   
2      126.0             48.0     -0.000085      0.504809     -0.007822   
3      126.0             48.0      0.000000      0.000000      0.000000   
4      121.0             48.0     -0.000163      0.504255      0.074896   

   TargetX  TargetY  TargetZ  Target  
0      0.0      0.5      0.0       0  
1      0.0      0.5      0.0       3  
2      0.0      0.5      0.0       3  
3      0.0      0.5      0.0       0  
4      0.0      0.5      0.0       8

In [10]:
data['Target'] = data['Target'].shift(-1)

In [11]:
data.head()

BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  ElbowRoll  \
0           0.0            0.0           0.0      -126.0        0.0   
1           0.0            5.0           0.0      -126.0        0.0   
2           0.0           10.0           0.0      -126.0        0.0   
3           0.0            0.0           0.0      -126.0        0.0   
4           0.0            0.0           0.0      -126.0        0.0   

   HandPitch  GripperRotation  EndEffectorX  EndEffectorY  EndEffectorZ  \
0      126.0             48.0      0.000000      0.000000      0.000000   
1      126.0             48.0     -0.000136      0.515677      0.036158   
2      126.0             48.0     -0.000085      0.504809     -0.007822   
3      126.0             48.0      0.000000      0.000000      0.000000   
4      121.0             48.0     -0.000163      0.504255      0.074896   

   TargetX  TargetY  TargetZ  Target  
0      0.0      0.5      0.0     3.0  
1      0.0      0.5      0.0     3.0  
2      0.0      0.5      0.0     0.0  
3      0.0      0.5      0.0     8.0  
4      0.0      0.5      0.0     3.0

In [12]:
data.tail()

BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  ElbowRoll  \
1812          -5.0      10.994705     -0.003428      -132.0  -0.000772   
1813          -5.0      10.994705     -0.003428      -138.0  -0.000772   
1814          -4.0      10.994705     -0.003428      -138.0  -0.000772   
1815          -4.0      10.994705     -0.003428      -139.0  -0.000772   
1816          -5.0      10.000000           NaN         NaN        NaN   

      HandPitch  GripperRotation  EndEffectorX  EndEffectorY  EndEffectorZ  \
1812      121.0        47.998825     -0.040930      0.467514      0.229924   
1813      121.0        47.998825     -0.036910      0.421763      0.191781   
1814      121.0        47.998825     -0.029557      0.422330      0.191787   
1815      121.0        47.998825     -0.028995      0.414355      0.185938   
1816        NaN              NaN           NaN           NaN           NaN   

       TargetX   TargetY  TargetZ  Target  
1812  0.346232 -0.042633    0.432     6.0  
1813  0.346232 -0.042633    0.432     1.0  
1814  0.346232 -0.042633    0.432     6.0  
1815  0.346232 -0.042633    0.432     0.0  
1816       NaN       NaN      NaN     NaN

In [13]:
data.drop(data.tail(2).index,inplace=True)
data.tail()

BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  ElbowRoll  \
1810     20.997234      10.994705     -0.003428 -126.991005  -0.000772   
1811     -5.000000      10.994705     -0.003428 -126.991005  -0.000772   
1812     -5.000000      10.994705     -0.003428 -132.000000  -0.000772   
1813     -5.000000      10.994705     -0.003428 -138.000000  -0.000772   
1814     -4.000000      10.994705     -0.003428 -138.000000  -0.000772   

      HandPitch  GripperRotation  EndEffectorX  EndEffectorY  EndEffectorZ  \
1810      121.0        47.998825      0.000036      0.504340      0.265195   
1811      121.0        47.998825     -0.043945      0.502420      0.265191   
1812      121.0        47.998825     -0.040930      0.467514      0.229924   
1813      121.0        47.998825     -0.036910      0.421763      0.191781   
1814      121.0        47.998825     -0.029557      0.422330      0.191787   

       TargetX   TargetY  TargetZ  Target  
1810  0.346232 -0.042633    0.432     2.0  
1811  0.346232 -0.042633    0.432     6.0  
1812  0.346232 -0.042633    0.432     6.0  
1813  0.346232 -0.042633    0.432     1.0  
1814  0.346232 -0.042633    0.432     6.0

In [14]:
X=data.drop("Target", axis=1)
y=data["Target"]

In [15]:
X.head()

BaseRotation  ShoulderPitch  ShoulderRoll  ElbowPitch  ElbowRoll  \
0           0.0            0.0           0.0      -126.0        0.0   
1           0.0            5.0           0.0      -126.0        0.0   
2           0.0           10.0           0.0      -126.0        0.0   
3           0.0            0.0           0.0      -126.0        0.0   
4           0.0            0.0           0.0      -126.0        0.0   

   HandPitch  GripperRotation  EndEffectorX  EndEffectorY  EndEffectorZ  \
0      126.0             48.0      0.000000      0.000000      0.000000   
1      126.0             48.0     -0.000136      0.515677      0.036158   
2      126.0             48.0     -0.000085      0.504809     -0.007822   
3      126.0             48.0      0.000000      0.000000      0.000000   
4      121.0             48.0     -0.000163      0.504255      0.074896   

   TargetX  TargetY  TargetZ  
0      0.0      0.5      0.0  
1      0.0      0.5      0.0  
2      0.0      0.5      0.0  
3      0.0      0.5      0.0  
4      0.0      0.5      0.0

In [16]:
Y.head()

NameError: name 'Y' is not defined

In [17]:
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)
dtree_model = DecisionTreeClassifier(max_depth = 121).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)

In [18]:
dtree_predictions

array([6., 2., 0., 4., 0., 0., 7., 3., 2., 4., 5., 0., 7., 1., 8., 2., 1.,
       6., 2., 6., 7., 8., 6., 0., 2., 3., 6., 2., 6., 0., 7., 6., 7., 3.,
       4., 1., 6., 7., 2., 3., 2., 2., 2., 3., 6., 3., 3., 2., 6., 1., 4.,
       8., 6., 2., 5., 5., 6., 2., 2., 1., 8., 8., 6., 1., 2., 5., 5., 2.,
       7., 7., 0., 8., 2., 2., 8., 5., 5., 7., 8., 3., 1., 3., 3., 8., 2.,
       5., 6., 0., 5., 7., 2., 2., 8., 3., 5., 5., 2., 1., 6., 8., 0., 5.,
       6., 3., 5., 8., 3., 7., 3., 5., 8., 3., 7., 8., 8., 0., 7., 6., 5.,
       6., 3., 7., 2., 2., 0., 1., 8., 6., 5., 1., 4., 6., 1., 1., 7., 3.,
       3., 8., 2., 0., 2., 7., 7., 8., 7., 2., 7., 3., 3., 1., 6., 4., 3.,
       3., 1., 6., 2., 7., 3., 0., 8., 6., 3., 5., 7., 6., 5., 3., 8., 2.,
       0., 6., 3., 6., 4., 2., 3., 3., 7., 8., 1., 4., 2., 8., 8., 7., 4.,
       2., 3., 6., 3., 7., 0., 1., 3., 3., 2., 8., 7., 3., 4., 1., 3., 6.,
       3., 2., 2., 1., 3., 6., 5., 8., 3., 6., 6., 6., 1., 6., 2., 3., 2.,
       1., 8., 0., 1., 2.

In [19]:
cm = confusion_matrix(y_test, dtree_predictions)

In [20]:
cm

array([[20,  2,  1,  3,  3,  2,  2,  7,  0],
       [ 0, 13,  1,  2,  2,  1,  3,  2,  4],
       [ 0,  1, 52,  9,  5,  6,  3,  4,  3],
       [ 1,  4,  6, 34,  1, 10,  2,  7,  1],
       [ 0,  4,  4,  2,  5,  2,  9,  4,  4],
       [ 0,  3,  5,  6,  3,  8,  2,  5,  1],
       [ 3,  5,  8,  4,  4,  4, 35,  3,  8],
       [ 2,  2,  8,  8,  1, 10,  1,  6,  3],
       [ 2,  1,  2,  4,  1,  1, 10,  2, 32]], dtype=int64)

In [33]:
from sklearn.metrics import classification_report
print(classification_report(y_test, dtree_predictions, target_names=['Nothing','BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp',
       'HandUp','HandDown']))

              precision    recall  f1-score   support

     Nothing       0.71      0.50      0.59        40
   BaseRight       0.37      0.46      0.41        28
    BaseLeft       0.60      0.63      0.61        83
ShoulderDown       0.47      0.52      0.49        66
  ShoulderUp       0.20      0.15      0.17        34
   ElbowDown       0.18      0.24      0.21        33
     ElbowUp       0.52      0.47      0.50        74
      HandUp       0.15      0.15      0.15        41
    HandDown       0.57      0.58      0.58        55

    accuracy                           0.45       454
   macro avg       0.42      0.41      0.41       454
weighted avg       0.46      0.45      0.45       454



In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import BaggingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import ExtraTreeClassifier
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier


In [35]:
bernouli=BernoulliNB(alpha=0.1)
#
logistic = LogisticRegression(random_state=0)

In [36]:
bernouli.fit(X_train, y_train)
bernouliPredict=bernouli.predict(X_test)
cm = confusion_matrix(y_test, bernouliPredict)

In [37]:
cm

array([[ 9,  0, 11,  4,  0,  0,  7,  7,  2],
       [ 0,  1, 13,  3,  0,  0,  7,  3,  1],
       [ 0,  1, 53,  4,  0,  0,  8, 14,  3],
       [ 0,  0, 30, 19,  0,  0,  9,  5,  3],
       [ 0,  1, 20,  1,  0,  0,  9,  2,  1],
       [ 0,  0, 18,  5,  0,  0,  6,  3,  1],
       [ 0,  0, 31,  4,  0,  0, 27, 10,  2],
       [ 0,  0, 17, 10,  0,  0,  4,  7,  3],
       [ 0,  1, 29,  2,  0,  0, 17,  5,  1]], dtype=int64)

In [38]:
print(classification_report(y_test, bernouliPredict, target_names=['Nothing','BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp']))

              precision    recall  f1-score   support

     Nothing       1.00      0.23      0.37        40
   BaseRight       0.25      0.04      0.06        28
    BaseLeft       0.24      0.64      0.35        83
ShoulderDown       0.37      0.29      0.32        66
  ShoulderUp       0.00      0.00      0.00        34
   ElbowDown       0.00      0.00      0.00        33
     ElbowUp       0.29      0.36      0.32        74
    HandDown       0.12      0.17      0.14        41
      HandUp       0.06      0.02      0.03        55

    accuracy                           0.26       454
   macro avg       0.26      0.19      0.18       454
weighted avg       0.27      0.26      0.22       454



C:\Users\batho\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\batho\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\batho\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [43]:
extra_tree = ExtraTreeClassifier(max_depth=139,splitter='best',random_state=0)
bagModel = BaggingClassifier(extra_tree, random_state=0).fit( X_train, y_train)
bagPredict = bagModel.predict(X_test)
cm = confusion_matrix(y_test, bagPredict)
cm

array([[20,  1,  1,  7,  2,  0,  3,  3,  3],
       [ 0, 16,  2,  1,  1,  0,  2,  2,  4],
       [ 1,  1, 55,  6,  5,  5,  5,  3,  2],
       [ 1,  7,  9, 30,  2,  8,  2,  3,  4],
       [ 0,  4,  5,  4,  9,  3,  6,  2,  1],
       [ 0,  5,  6,  5,  6,  8,  1,  2,  0],
       [ 2,  6,  8,  6,  5,  3, 33,  2,  9],
       [ 1,  6,  9,  8,  0,  7,  2,  4,  4],
       [ 2,  3,  1,  5,  1,  0,  9,  1, 33]], dtype=int64)

In [44]:
print(classification_report(y_test, bagPredict, target_names=['Nothing','BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp']))

              precision    recall  f1-score   support

     Nothing       0.74      0.50      0.60        40
   BaseRight       0.33      0.57      0.42        28
    BaseLeft       0.57      0.66      0.61        83
ShoulderDown       0.42      0.45      0.43        66
  ShoulderUp       0.29      0.26      0.28        34
   ElbowDown       0.24      0.24      0.24        33
     ElbowUp       0.52      0.45      0.48        74
    HandDown       0.18      0.10      0.13        41
      HandUp       0.55      0.60      0.57        55

    accuracy                           0.46       454
   macro avg       0.43      0.43      0.42       454
weighted avg       0.46      0.46      0.45       454



In [45]:
gaussian=GaussianNB()
gaussian.fit(X_train, y_train)
gaussianPredict=gaussian.predict(X_test)
cm = confusion_matrix(y_test, gaussianPredict)
cm

array([[15,  0, 11,  2,  0,  5,  5,  1,  1],
       [ 3,  0, 17,  0,  1,  2,  2,  3,  0],
       [ 2,  1, 53,  3,  0,  9,  9,  4,  2],
       [10,  0, 29,  2,  0, 18,  2,  4,  1],
       [ 2,  2,  9,  0,  0, 10,  9,  0,  2],
       [ 3,  1, 14,  1,  0,  8,  4,  2,  0],
       [21,  0, 23,  4,  0,  7, 16,  2,  1],
       [ 5,  0, 21,  2,  0,  4,  3,  4,  2],
       [19,  0, 24,  0,  0,  4,  5,  3,  0]], dtype=int64)

In [46]:
print(classification_report(y_test, gaussianPredict, target_names=['Nothing','BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp']))

              precision    recall  f1-score   support

     Nothing       0.19      0.38      0.25        40
   BaseRight       0.00      0.00      0.00        28
    BaseLeft       0.26      0.64      0.37        83
ShoulderDown       0.14      0.03      0.05        66
  ShoulderUp       0.00      0.00      0.00        34
   ElbowDown       0.12      0.24      0.16        33
     ElbowUp       0.29      0.22      0.25        74
    HandDown       0.17      0.10      0.13        41
      HandUp       0.00      0.00      0.00        55

    accuracy                           0.22       454
   macro avg       0.13      0.18      0.13       454
weighted avg       0.16      0.22      0.16       454



In [54]:
knc = KNeighborsClassifier(algorithm='kd_tree', leaf_size=16, n_neighbors=9)
knc.fit(X_train, y_train)
kncPredict=knc.predict(X_test)
cm = confusion_matrix(y_test, kncPredict)
cm

array([[17,  2,  1,  5,  3,  1,  4,  4,  3],
       [ 2, 15,  5,  2,  1,  0,  0,  1,  2],
       [ 2,  2, 59,  4,  0,  3,  6,  3,  4],
       [ 3,  4, 10, 29,  2,  4,  4,  5,  5],
       [ 2,  3,  4,  3,  6,  1,  7,  6,  2],
       [ 2,  4,  6,  6,  4,  5,  1,  4,  1],
       [ 1,  7,  9,  8,  2,  3, 22,  4, 18],
       [ 1,  4, 14, 13,  1,  4,  2,  0,  2],
       [ 2,  4,  6,  3,  2,  0,  6,  3, 29]], dtype=int64)

In [55]:
print(classification_report(y_test, kncPredict, target_names=['Nothing','BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp']))

              precision    recall  f1-score   support

     Nothing       0.53      0.42      0.47        40
   BaseRight       0.33      0.54      0.41        28
    BaseLeft       0.52      0.71      0.60        83
ShoulderDown       0.40      0.44      0.42        66
  ShoulderUp       0.29      0.18      0.22        34
   ElbowDown       0.24      0.15      0.19        33
     ElbowUp       0.42      0.30      0.35        74
    HandDown       0.00      0.00      0.00        41
      HandUp       0.44      0.53      0.48        55

    accuracy                           0.40       454
   macro avg       0.35      0.36      0.35       454
weighted avg       0.38      0.40      0.38       454



In [66]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(StandardScaler(), LogisticRegression(solver='sag', max_iter=4000,random_state=0))
pipe.fit(X_train, y_train)
logisticPredict=pipe.predict(X_test)
cm = confusion_matrix(y_test, logisticPredict)
cm

array([[21,  0,  5,  4,  2,  2,  0,  1,  5],
       [ 1,  2,  9,  4,  3,  0,  3,  1,  5],
       [ 1,  1, 54,  8,  2,  0, 10,  2,  5],
       [ 4,  0, 25, 29,  1,  1,  4,  1,  1],
       [ 4,  3, 13,  2,  0,  4,  4,  0,  4],
       [ 5,  0,  9,  8,  2,  3,  3,  3,  0],
       [ 5,  1, 27,  5,  1,  4, 16,  2, 13],
       [ 9,  1,  3, 17,  1,  5,  4,  0,  1],
       [ 4,  1, 21,  1,  2,  3,  5,  0, 18]], dtype=int64)

In [67]:
print(classification_report(y_test, logisticPredict, target_names=['Nothing','BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp']))

              precision    recall  f1-score   support

     Nothing       0.39      0.53      0.45        40
   BaseRight       0.22      0.07      0.11        28
    BaseLeft       0.33      0.65      0.43        83
ShoulderDown       0.37      0.44      0.40        66
  ShoulderUp       0.00      0.00      0.00        34
   ElbowDown       0.14      0.09      0.11        33
     ElbowUp       0.33      0.22      0.26        74
    HandDown       0.00      0.00      0.00        41
      HandUp       0.35      0.33      0.34        55

    accuracy                           0.31       454
   macro avg       0.24      0.26      0.23       454
weighted avg       0.27      0.31      0.27       454



In [91]:
pipeRandom = make_pipeline(StandardScaler(), RandomForestClassifier(n_estimators=1000, random_state=0))
pipeRandom.fit(X_train, y_train)
randomForestPredict=pipeRandom.predict(X_test)
cm = confusion_matrix(y_test, randomForestPredict)
cm

array([[17,  1,  0,  7,  2,  1,  3,  5,  4],
       [ 0, 16,  2,  3,  1,  1,  1,  2,  2],
       [ 0,  0, 57,  3,  4,  5,  5,  4,  5],
       [ 3,  4,  6, 36,  0,  6,  1,  8,  2],
       [ 0,  3,  3,  1,  7,  3,  9,  4,  4],
       [ 0,  4,  6,  4,  5,  9,  1,  3,  1],
       [ 1,  5,  7,  6,  3,  2, 31,  4, 15],
       [ 1,  2, 12,  6,  1,  6,  2,  8,  3],
       [ 2,  2,  1,  3,  2,  0, 10,  1, 34]], dtype=int64)

In [92]:
print(classification_report(y_test, randomForestPredict, target_names=['Nothing','BaseRight', 'BaseLeft',
       'ShoulderDown', 'ShoulderUp', 'ElbowDown', 'ElbowUp', 'HandDown',
       'HandUp']))

              precision    recall  f1-score   support

     Nothing       0.71      0.42      0.53        40
   BaseRight       0.43      0.57      0.49        28
    BaseLeft       0.61      0.69      0.64        83
ShoulderDown       0.52      0.55      0.53        66
  ShoulderUp       0.28      0.21      0.24        34
   ElbowDown       0.27      0.27      0.27        33
     ElbowUp       0.49      0.42      0.45        74
    HandDown       0.21      0.20      0.20        41
      HandUp       0.49      0.62      0.54        55

    accuracy                           0.47       454
   macro avg       0.44      0.44      0.43       454
weighted avg       0.47      0.47      0.47       454



In [93]:
sum=0
for i in range(len(cm)):
    for j in range(len(cm[0])):
        if i==j:
            sum+=cm[i][j]
print(sum)
print(len(y_test))

215
454


In [90]:
print(212/454)

0.4669603524229075
